version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    env_file:
      - .env.prod
    depends_on:
      - mongo
    restart: always
    command: npm start

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_prod_data:/data/db
    restart: always

volumes:
  mongodb_prod_data:
