export const ERROR_TYPES = {
  DATABASE: "DATABASE_ERROR",
  VALIDATION: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND_ERROR",
  AUTH: "AUTHENTICATION_ERROR",
  RATE_LIMIT: "RATE_LIMIT_EXCEEDED",
  INTERNAL: "INTERNAL_SERVER_ERROR",
};

export const HTTP_CODES = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_ERROR: 500,
};
